export const en = {
  meta: {
    title: "FOUCH — Entertainment Predictions",
    description:
      "Predict entertainment's biggest moments and see how your picks compare with the world.",
  },
  nav: { wordmark: "FOUCH", language: "Language" },
  hero: {
    eyebrow: "Entertainment Predictions",
    headlineLines: ["Make", "your", "call."],
    subhead: "Predict it. See what the crowd thinks. Prove you called it.",
    cta: "Start predicting",
    predictionsOpen: "Predictions Open",
    predictLabel: "Predict",
    predictHint: "Build your Top 10",
    competeLabel: "Compete",
    competeHint: "See what the crowd thinks",
    proveLabel: "Prove it",
  },
  featuredEvent: {
    eyebrowUpcoming: "Upcoming",
    eyebrowNow: "Now Predicting",
    eyebrowClosed: "Predictions Closed",
    prompt: "Who makes your Top 10?",
    cta: "Make your Top 10",
    viewLeaderboard: "View leaderboard →",
  },
  crowd: {
    title: "The Crowd",
    earlyTitle: "It's early.",
    earlyBody: "The first calls are coming in. Make yours before the crowd starts taking shape.",
    earlyCta: "Make your call →",
    question: "Who does the crowd have winning?",
    viewAll: "View all →",
    basedOn: "Based on {n} predictions",
  },
  howItWorks: {
    title: "How it works",
    steps: [
      { title: "Predict", body: "Build your ranking." },
      { title: "Compete", body: "See how your picks compare." },
      { title: "Prove it", body: "Get scored when the results are in." },
    ],
    you: "You",
    crowd: "Crowd",
    excellent: "Excellent",
    exampleScore: "Example score",
  },
  closing: {
    lineOne: "Everyone has a take.",
    lineTwo: "FOUCH keeps the receipts.",
    tagline: "Predict · Compete · Prove it",
    cta: "Make your call",
  },
  eventPage: {
    back: "Back to Fouch",
    comingSoon: "The prediction builder for this event opens soon.",
  },
  footer: {
    tagline: "Entertainment predictions.",
    disclaimer:
      "FOUCH is an independent entertainment prediction game. Not affiliated with or endorsed by the events, organizations, or participants featured on the platform.",
    privacy: "Privacy",
    terms: "Terms",
  },
  builder: {
    metaTitle: "Build your Top 10 — {event}",
    metaDescription: "Choose the 10 contestants you think will go furthest.",
    backToFouch: "Back to Fouch",
    backToBuilder: "Back to builder",
    noParticipants: "No participants are available for this event yet. Check back soon.",
    buildTitle: "Build your Top {n}",
    buildHint: "Choose the {n} contestants you think will go furthest.",
    yourTop: "Your Top {n}",
    topReady: "Your Top {n} is ready.",
    reviewCta: "Review my prediction",
    allContestants: "All contestants",
    selectedCount: "{count} / {total} selected",
    searchPlaceholder: "Search countries...",
    searchAria: "Search countries",
    selected: "Selected",
    noMatch: "No countries match “{query}”.",
    emptyList: "Tap a country below to give it position 01.",
    replaceBadge: "Replace",
    replaceTitle: "No longer available — remove and pick a current contestant to save changes.",
    replaceHint: "Replace the contestant marked \"Replace\" with a current one to save your changes.",
    moveUpAria: "Move {name} up, currently position {pos} of {total}",
    moveDownAria: "Move {name} down, currently position {pos} of {total}",
    removeAria: "Remove {name} from your Top {total}",
    demoNote: "Demo participant data — not the official lineup",
    listUpdated: "Contestant list updated {date}",
  },
  review: {
    metaTitle: "Your Top 10 — {event}",
    yourTop: "Your Top {n}",
    incomplete: "We don't have a complete prediction for this event yet on this device.",
    buildCta: "Build your Top {n}",
    editCta: "Edit my Top {n}",
    nickname: "Nickname",
    country: "Country",
    optional: "Optional",
    optionalNote:
      "Optional — shown publicly with your prediction. You can update your picks until predictions close.",
    saving: "Saving…",
    saveCta: "Save my Top {n}",
    tryAgain: "Try again",
    tryingAgain: "Trying again…",
  },
  auth: {
    headingCreate: "Verify your email to save your prediction.",
    headingEdit: "Verify your email to save your changes.",
    subheading: "We'll send you a verification code — no password needed.",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    sending: "Sending…",
    sendCode: "Send code",
    privacyNote:
      "FOUCH is an independent fan prediction game — your email is only used to verify your call, never shown publicly.",
    enterCode: "Enter the code we sent to {email}.",
    codeLabel: "Verification code",
    tooManyAttempts: "Too many incorrect attempts. Request a new code.",
    verifying: "Verifying…",
    verifyCta: "Verify and lock",
    resendCode: "Resend code",
    resendIn: "Resend code in 0:{s}",
    differentEmail: "Use a different email",
    sendFailed: "We couldn't send a code — try again in a moment.",
    verifyFailed: "We couldn't verify your code — try again.",
    lockFailed: "We couldn't save your prediction. Your Top 10 is still saved — try again.",
    editFailed: "We couldn't save your changes. Try again.",
  },
  publicPrediction: {
    titleWithName: "{name}'s Top 10",
    titleAnonymous: "Someone's Top 10",
    metaTitleNamed: "{name}'s Top 10 — {event}",
    metaTitleAnon: "A Top 10 prediction — {event}",
    metaDescription: "See the prediction, then make your own call.",
    demoBanner: "Demo prediction — not the official lineup",
    callIsIn: "YOUR CALL IS IN",
    updateUntil: "You can update your picks until {when}.",
    callLocked: "YOUR CALL IS LOCKED",
    editCta: "Edit my Top 10",
    shareHeading: "Share your call",
    originalPrediction: "Your original prediction",
    makeYourTop: "Make your Top 10",
    editTitle: "Edit your Top {n}",
  },
  share: {
    story: "Story",
    post: "Post",
    instagramStory: "Instagram Story",
    preparing: "Preparing…",
    share: "Share",
    saveImage: "Save image",
    copyLink: "Copy link",
    copied: "Copied",
    copyPredictionLink: "Copy prediction link",
    storyReady: "Your Story is ready",
    storyReadyMobile: "Image saved. Open Instagram → Story → choose the image.",
    storyReadyDesktop: "Open Instagram on your phone and add the saved image to your Story.",
    shareTitle: "My Fouch prediction",
    predictionCardAlt: "Your Fouch prediction card",
    resultCardAlt: "Your Fouch result card",
    shareResult: "Share your result",
    cardHeadline: "MAKE YOUR CALL.",
    cardFooter: "WHO YOU GOT?",
    cardDemo: "DEMO",
    cardWinner: "Winner",
    cardCorrect: "Correct",
    cardMissed: "Missed",
    cardPodium: "Podium",
    cardTop5: "Top 5",
    cardTop10: "Top 10",
    cardTopPct: "TOP {n}%",
    cardWorldwide: "WORLDWIDE",
    cardBeatIt: "THINK YOU COULD BEAT IT?",
    ogHeadingNamed: "{name}'s Top 10",
    ogHeadingAnon: "A Top 10 prediction",
  },
  community: {
    youVsWorld: "You vs the World",
    demoNote: "Demo community data — not official {noun}",
    earlyTitle: "You're early.",
    earlyBody: "Be the first to set the pace.",
    forming: "The crowd is just forming — {n} other {noun} in so far.",
    nounOne: "prediction",
    nounMany: "predictions",
    earlySignal: "Early signal · based on {n} other predictions",
    sameWinner: "Same winner",
    nobodySameCall: "nobody else made the same call.",
    sameWinnerCount: "{count} of {total} other predictions agree.",
    sameWinnerPct: "{pct} of the world agrees. Based on {total} other predictions.",
    top3Match: "Top 3 match",
    youShare: "You share {n} of your top 3 with the world.",
    picked: "{ratio} picked",
    avgPos: "avg #{n}",
    basedOnOne: "Based on {n} other prediction.",
    basedOnMany: "Based on {n} other predictions.",
    boldest: "Your boldest call",
    boldestCount: "Only {count} of {total} other predictions have this in their top 10.",
    boldestPct: "Only {pct} of other predictions have this in their top 10.",
    worldTop10: "The world's top 10",
    worldTop10Hint: "Ranked by how high each pick appears across predictions.",
    shareStandsOut: "Your call stands out.",
    shareWrong: "Think the world is wrong?",
    shareCta: "Share your call",
    crowdChanged: "Your crowd changed",
    crowdMovingToward: "The crowd is moving toward your call.",
    crowdMovingAway: "The crowd is moving away from your call.",
    crowdBasedOn: "Based on community predictions since your call.",
    pts: "pts",
  },
  score: {
    title: "Fouch score",
    demoResult: "Demo result — not an official outcome",
    bands: {
      MISSED_IT: "Missed it",
      FAIR: "Fair call",
      GOOD: "Good call",
      EXCELLENT: "Excellent call",
      ELITE: "Elite call",
    },
    winner: "Winner",
    correct: "Correct",
    missed: "✗ Missed — your pick:",
    actual: "Actual:",
    podium: "Podium",
    top5: "Top 5",
    top10: "Top 10",
    ranking: "Ranking",
    closeness: "How close your picks were to the official finish.",
    seeFinish: "See where you finished",
    beat: "You beat {pct}% of {noun} for this event, based on {n} other predictions.",
    worldUnlocks: "World ranking unlocks at {n} predictions.",
  },
  leaderboard: {
    back: "FOUCH",
    title: "Event leaderboard",
    subtitle: "See who called it best.",
    demoNote: "Demo leaderboard — not an official outcome",
    locked: "Leaderboard locked",
    makeCall: "Make your call",
    none: "No scored predictions yet.",
    first: "First call on the board.",
    starting: "The leaderboard is just getting started.",
    yourFinish: "Your finish",
    topPct: "Top {n}%",
    neighborhood: "Your neighborhood",
    you: "You",
    lockedBody: "Results will appear here once {event} has been scored.",
    rankOf: "#{rank} of {total}",
    scoreLine: "Fouch score {score}",
    worldUnlocks: "World ranking unlocks at {n} predictions.",
    metaTitle: "{event} Predictions Leaderboard | FOUCH",
    metaDemo: "A demo FOUCH predictions leaderboard — not an official result.",
    metaLive: "See how FOUCH predictions ranked after the result.",
  },
  lock: {
    notOpen: "Predictions for this event haven't opened yet.",
    locked: "Predictions for this event are locked.",
  },
  errors: {
    generic: "Something went wrong. Try again.",
  },
};
