import type { Dictionary } from "./types";

/**
 * Neutral conversational Latin American Spanish — no country-specific
 * slang. Typed as Dictionary, so any key missing here fails the
 * typecheck. Brand name FOUCH and official event/contestant names are
 * never translated.
 */
export const es: Dictionary = {
  meta: {
    title: "FOUCH — Predicciones de entretenimiento",
    description:
      "Predice los grandes momentos del entretenimiento y descubre cómo se comparan tus elecciones con las del mundo.",
  },
  nav: { wordmark: "FOUCH", language: "Idioma" },
  hero: {
    eyebrow: "Predicciones de entretenimiento",
    headlineLines: ["Haz", "tu", "predicción."],
    subhead: "Predice. Descubre qué piensa la comunidad. Demuestra que acertaste.",
    cta: "Empieza a predecir",
    predictionsOpen: "Predicciones abiertas",
    predictLabel: "Predice",
    predictHint: "Arma tu Top 10",
    competeLabel: "Compite",
    competeHint: "Mira qué piensa la comunidad",
    proveLabel: "Demuéstralo",
  },
  featuredEvent: {
    eyebrowUpcoming: "Próximamente",
    eyebrowNow: "Predicciones abiertas",
    eyebrowClosed: "Predicciones cerradas",
    prompt: "¿Quiénes están en tu Top 10?",
    cta: "Arma tu Top 10",
    viewLeaderboard: "Ver clasificación →",
  },
  crowd: {
    title: "La comunidad",
    earlyTitle: "Es temprano.",
    earlyBody: "Están llegando las primeras predicciones. Haz la tuya antes de que la comunidad tome forma.",
    earlyCta: "Haz tu predicción →",
    question: "¿A quién ve ganando la comunidad?",
    viewAll: "Ver todo →",
    basedOn: "Basado en {n} predicciones",
  },
  howItWorks: {
    title: "Cómo funciona",
    steps: [
      { title: "Predice", body: "Arma tu ranking." },
      { title: "Compite", body: "Mira cómo se comparan tus elecciones." },
      { title: "Demuéstralo", body: "Recibe tu puntaje cuando salgan los resultados." },
    ],
    you: "Tú",
    crowd: "Comunidad",
    excellent: "Excelente",
    exampleScore: "Puntaje de ejemplo",
  },
  closing: {
    lineOne: "Todos tienen una opinión.",
    lineTwo: "FOUCH guarda el comprobante.",
    tagline: "Predice · Compite · Demuéstralo",
    cta: "Haz tu predicción",
  },
  eventPage: {
    back: "Volver a Fouch",
    comingSoon: "El armador de predicciones de este evento abre pronto.",
  },
  footer: {
    tagline: "Predicciones de entretenimiento.",
    disclaimer:
      "FOUCH es un juego independiente de predicciones de entretenimiento. No está afiliado ni respaldado por los eventos, organizaciones o participantes que aparecen en la plataforma.",
    privacy: "Privacidad",
    terms: "Términos",
  },
  builder: {
    metaTitle: "Arma tu Top 10 — {event}",
    metaDescription: "Elige a las 10 participantes que crees que llegarán más lejos.",
    backToFouch: "Volver a Fouch",
    backToBuilder: "Volver al armador",
    noParticipants: "Todavía no hay participantes disponibles para este evento. Vuelve pronto.",
    buildTitle: "Arma tu Top {n}",
    buildHint: "Elige a las {n} participantes que crees que llegarán más lejos.",
    yourTop: "Tu Top {n}",
    topReady: "Tu Top {n} está listo.",
    reviewCta: "Revisar mi predicción",
    allContestants: "Todas las participantes",
    selectedCount: "{count} / {total} elegidas",
    searchPlaceholder: "Buscar países...",
    searchAria: "Buscar países",
    selected: "Elegida",
    noMatch: "Ningún país coincide con “{query}”.",
    emptyList: "Toca un país abajo para darle la posición 01.",
    replaceBadge: "Reemplazar",
    replaceTitle: "Ya no está disponible — quítala y elige a una participante vigente para guardar los cambios.",
    replaceHint: "Reemplaza a la participante marcada como \"Reemplazar\" por una vigente para guardar tus cambios.",
    moveUpAria: "Subir a {name}, actualmente en la posición {pos} de {total}",
    moveDownAria: "Bajar a {name}, actualmente en la posición {pos} de {total}",
    removeAria: "Quitar a {name} de tu Top {total}",
    demoNote: "Datos de participantes de demostración — no es la lista oficial",
    listUpdated: "Lista de participantes actualizada el {date}",
  },
  review: {
    metaTitle: "Tu Top 10 — {event}",
    yourTop: "Tu Top {n}",
    incomplete: "Todavía no tenemos una predicción completa para este evento en este dispositivo.",
    buildCta: "Arma tu Top {n}",
    editCta: "Editar mi Top {n}",
    nickname: "Apodo",
    country: "País",
    optional: "Opcional",
    optionalNote:
      "Opcional — se muestra públicamente junto a tu predicción. Puedes actualizar tus elecciones hasta que cierren las predicciones.",
    saving: "Guardando…",
    saveCta: "Guardar mi Top {n}",
    tryAgain: "Intentar de nuevo",
    tryingAgain: "Intentando de nuevo…",
  },
  auth: {
    headingCreate: "Verifica tu correo para guardar tu predicción.",
    headingEdit: "Verifica tu correo para guardar tus cambios.",
    subheading: "Te enviaremos un código de verificación — sin contraseñas.",
    emailLabel: "Correo electrónico",
    emailPlaceholder: "tu@ejemplo.com",
    sending: "Enviando…",
    sendCode: "Enviar código",
    privacyNote:
      "FOUCH es un juego independiente de predicciones entre fans — tu correo solo se usa para verificar tu predicción y nunca se muestra públicamente.",
    enterCode: "Ingresa el código que enviamos a {email}.",
    codeLabel: "Código de verificación",
    tooManyAttempts: "Demasiados intentos incorrectos. Solicita un código nuevo.",
    verifying: "Verificando…",
    verifyCta: "Verificar y guardar",
    resendCode: "Reenviar código",
    resendIn: "Reenviar código en 0:{s}",
    differentEmail: "Usar otro correo",
    sendFailed: "No pudimos enviar el código — inténtalo de nuevo en un momento.",
    verifyFailed: "No pudimos verificar tu código — inténtalo de nuevo.",
    lockFailed: "No pudimos guardar tu predicción. Tu Top 10 sigue guardado — inténtalo de nuevo.",
    editFailed: "No pudimos guardar tus cambios. Inténtalo de nuevo.",
  },
  publicPrediction: {
    titleWithName: "El Top 10 de {name}",
    titleAnonymous: "El Top 10 de alguien",
    metaTitleNamed: "El Top 10 de {name} — {event}",
    metaTitleAnon: "Una predicción Top 10 — {event}",
    metaDescription: "Mira la predicción y luego haz la tuya.",
    demoBanner: "Predicción de demostración — no es la lista oficial",
    callIsIn: "TU PREDICCIÓN ESTÁ REGISTRADA",
    updateUntil: "Puedes actualizar tus elecciones hasta el {when}.",
    callLocked: "TU PREDICCIÓN ESTÁ BLOQUEADA",
    editCta: "Editar mi Top 10",
    shareHeading: "Comparte tu predicción",
    originalPrediction: "Tu predicción original",
    makeYourTop: "Arma tu Top 10",
    editTitle: "Edita tu Top {n}",
  },
  share: {
    story: "Historia",
    post: "Publicación",
    instagramStory: "Historia de Instagram",
    preparing: "Preparando…",
    share: "Compartir",
    saveImage: "Guardar imagen",
    copyLink: "Copiar enlace",
    copied: "Copiado",
    copyPredictionLink: "Copiar enlace de la predicción",
    storyReady: "Tu historia está lista",
    storyReadyMobile: "Imagen guardada. Abre Instagram → Historia → elige la imagen.",
    storyReadyDesktop: "Abre Instagram en tu teléfono y agrega la imagen guardada a tu historia.",
    shareTitle: "Mi predicción en Fouch",
    predictionCardAlt: "Tu tarjeta de predicción de Fouch",
    resultCardAlt: "Tu tarjeta de resultado de Fouch",
    shareResult: "Comparte tu resultado",
    cardHeadline: "HAZ TU PREDICCIÓN.",
    cardFooter: "¿CUÁL ES EL TUYO?",
    cardDemo: "DEMO",
    cardWinner: "Ganadora",
    cardCorrect: "Acertaste",
    cardMissed: "Fallaste",
    cardPodium: "Podio",
    cardTop5: "Top 5",
    cardTop10: "Top 10",
    cardTopPct: "TOP {n}%",
    cardWorldwide: "A NIVEL MUNDIAL",
    cardBeatIt: "¿CREES QUE PUEDES SUPERARLO?",
    ogHeadingNamed: "El Top 10 de {name}",
    ogHeadingAnon: "Una predicción Top 10",
  },
  community: {
    youVsWorld: "Tú vs el mundo",
    demoNote: "Datos de comunidad de demostración — no son {noun} oficiales",
    earlyTitle: "Llegaste temprano.",
    earlyBody: "Sé la primera persona en marcar el ritmo.",
    forming: "La comunidad apenas se está formando — {n} {noun} más por ahora.",
    nounOne: "predicción",
    nounMany: "predicciones",
    earlySignal: "Señal temprana · basada en {n} predicciones más",
    sameWinner: "Misma ganadora",
    nobodySameCall: "nadie más hizo la misma predicción.",
    sameWinnerCount: "{count} de {total} predicciones más coinciden.",
    sameWinnerPct: "El {pct} del mundo coincide. Basado en {total} predicciones más.",
    top3Match: "Coincidencia en el Top 3",
    youShare: "Compartes {n} de tu Top 3 con el mundo.",
    picked: "{ratio} la eligió",
    avgPos: "prom. #{n}",
    basedOnOne: "Basado en {n} predicción más.",
    basedOnMany: "Basado en {n} predicciones más.",
    boldest: "Tu elección más arriesgada",
    boldestCount: "Solo {count} de {total} predicciones más la tienen en su top 10.",
    boldestPct: "Solo el {pct} de las demás predicciones la tiene en su top 10.",
    worldTop10: "El top 10 del mundo",
    worldTop10Hint: "Ordenado según qué tan alto aparece cada elección en las predicciones.",
    shareStandsOut: "Tu predicción destaca.",
    shareWrong: "¿Crees que el mundo se equivoca?",
    shareCta: "Comparte tu predicción",
    crowdChanged: "Tu comunidad cambió",
    crowdMovingToward: "La comunidad se está acercando a tu predicción.",
    crowdMovingAway: "La comunidad se está alejando de tu predicción.",
    crowdBasedOn: "Basado en las predicciones de la comunidad desde la tuya.",
    pts: "pts",
  },
  score: {
    title: "Puntaje Fouch",
    demoResult: "Resultado de demostración — no es un resultado oficial",
    bands: {
      MISSED_IT: "No acertaste",
      FAIR: "Predicción aceptable",
      GOOD: "Buena predicción",
      EXCELLENT: "Excelente predicción",
      ELITE: "Predicción de élite",
    },
    winner: "Ganadora",
    correct: "Correcto",
    missed: "✗ Fallaste — tu elección:",
    actual: "Real:",
    podium: "Podio",
    top5: "Top 5",
    top10: "Top 10",
    ranking: "Ranking",
    closeness: "Qué tan cerca estuvieron tus elecciones del resultado oficial.",
    seeFinish: "Mira dónde quedaste",
    beat: "Superaste al {pct}% de las {noun} de este evento, según {n} predicciones más.",
    worldUnlocks: "El ranking mundial se desbloquea con {n} predicciones.",
  },
  leaderboard: {
    back: "FOUCH",
    title: "Clasificación del evento",
    subtitle: "Mira quién acertó mejor.",
    demoNote: "Clasificación de demostración — no es un resultado oficial",
    locked: "Clasificación bloqueada",
    makeCall: "Haz tu predicción",
    none: "Todavía no hay predicciones con puntaje.",
    first: "La primera predicción en la tabla.",
    starting: "La clasificación apenas está comenzando.",
    yourFinish: "Tu resultado",
    topPct: "Top {n}%",
    neighborhood: "Tu zona de la tabla",
    you: "Tú",
    lockedBody: "Los resultados aparecerán aquí cuando {event} haya sido puntuado.",
    rankOf: "#{rank} de {total}",
    scoreLine: "Puntaje Fouch {score}",
    worldUnlocks: "El ranking mundial se desbloquea con {n} predicciones.",
    metaTitle: "Clasificación de predicciones de {event} | FOUCH",
    metaDemo: "Una clasificación de demostración de predicciones de FOUCH — no es un resultado oficial.",
    metaLive: "Mira cómo quedaron las predicciones de FOUCH tras el resultado.",
  },
  lock: {
    notOpen: "Las predicciones de este evento todavía no han abierto.",
    locked: "Las predicciones de este evento están cerradas.",
  },
  errors: {
    generic: "Algo salió mal. Inténtalo de nuevo.",
  },
};
